on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Fetch Build Keyboards
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install yaml2json
        run: python3 -m pip install remarshal
      - id: set-matrix
        name: Fetch Build Matrix
        run: |
          matrix=$(yaml2json build.yaml | jq -c .)
          echo $matrix
          yaml2json build.yaml
          echo "::set-output name=matrix::${matrix}"
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    needs: matrix
    name: Build
    strategy:
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (${{ matrix.board }} ${{ matrix.shield }})
        run: |
          export cmake_args="-DZMK_CONFIG=${GITHUB_WORKSPACE}/config"
          if [ -n "${{ matrix.shield }}" ]; then export cmake_args="-DSHIELD=${{ matrix.shield }} ${cmake_args}"; fi
          west build -s zmk/app -b ${{ matrix.board }} -- ${cmake_args}
      - name: ${{ matrix.board }} ${{ matrix.shield }} DTS File
        if: ${{ always() }}
        run: |
          if [ -f "build/zephyr/${{ matrix.board }}.pre.tmp" ]; then cat -n build/zephyr/${{ matrix.board }}.pre.tmp; fi
          if [ -f "build/zephyr/zephyr.dts" ]; then cat -n build/zephyr/zephyr.dts; fi
      - name: ${{ matrix.board }}  ${{ matrix.shield }} Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: if [ -f "build/zephyr/zmk.uf2" ]; then cp build/zephyr/zmk.uf2 ${{ matrix.board }}-${{ matrix.shield }}.uf2; fi
      - name: Archive (${{ matrix.board }} ${{ matrix.shield }})
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ matrix.board }}-${{ matrix.shield }}.uf2
